### ISSUE TITLE
Repeated definition

### ISSUE THREAD

**Issue by scottamoore** [r-wasm/quarto-live#76] opened 2024-11-22 08:42 UTC
In the table under "Checking environment", the definitions of `.last_value` and `.result` are the same ("The last value of the evaluated learner code."). I'm guessing they should be different?

**Comment by georgestagg** [comment] 2024-11-22 08:52
It's not clear in the docs, but it is as intended.

The purpose is to smooth the transisiton for users who may have used [{learnr}'s custom grading](https://rstudio.github.io/learnr/articles/exercises.html#custom-checking) where the result is stored in `.last_value`.

Closing for now, but we might revisit in the far future to tidy this up.

**Closed by georgestagg** 2024-11-22 08:52 UTC
